version: '3.6'

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rootapp123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  worker:
    build: .
    command: celery worker --app rootapp --loglevel info --logfile celery-worker.log
    volumes:
      - .:/code
    depends_on:
      - redis
  schedule:
    build: .
    command: celery beat --app rootapp --loglevel info --logfile celery-beat.log
    volumes:
      - .:/code
    depends_on:
      - redis
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  document:
    image: swaggerapi/swagger-ui
    volumes:
      - .:/app
    ports:
      - "1234:8080"
    environment:
      SWAGGER_JSON: /app/docs/openapi.json
  nginx:
    build: ./nginx-config
    ports:
      - 80:80
    links:
      - web
    depends_on:
      - web
volumes:
  postgres_data:
  redis_data:
